### ISSUE TITLE
Please create new releases with proper git tags

### ISSUE THREAD

**Issue by rhertzog** [stathissideris/ditaa#11]
Hello,

most distributions still provide very old versions of ditaa becaue you have not made any proper upstream releases since version 0.9. Please consider releasing 0.10 with a proper git tag at least (so that it appears in the "release" tag in github).

You should probably also document that ditaa moved away from sourceforge to github on http://ditaa.sourceforge.net ...

Thank you!

**Comment by fommil** [comment]
And accept my PR the remove the debugging noise :-)

**Comment by rhertzog** [comment]
@stathissideris Ping. Any chance you could make a proper release one of those days ?

**Comment by fommil** [comment]
@stathissideris if you make the release, Raphael will be packaging it for Debian. Can you please accept and then tag the version https://github.com/stathissideris/ditaa/pull/8 ?

**Comment by stathissideris** [comment]
Done, sorry for the delay, I was on an extended holiday.
