### ISSUE TITLE
0.10 release calls itself 0.9

### ISSUE THREAD

**Issue by geoffholden** [stathissideris/ditaa#14]
When building the 0.10 release, the output jar file is still called ditaa0_9.jar.
The version.string property in release.xml didn't get updated.

**Comment by geoffholden** [comment]
Patch attached.
[versionnumber.patch.txt](https://github.com/stathissideris/ditaa/files/103224/versionnumber.patch.txt)

**Comment by apjanke** [comment]
Instead of just attaching the patch to an issue, if you fork the repo and make it a Pull Request, it'll be easier for the repo developers to evaluate (plus you'll get author credit in the commit history once it's merged).
