### ISSUE TITLE
Allow SVG export

### ISSUE THREAD

**Issue by roipoussiere** [stathissideris/ditaa#23]
Some PlantUML tools work with svg, such as the [Atom markdown-preview-enhanced
 plugin](https://github.com/shd101wyy/markdown-preview-enhanced/issues/258).

Since ditaa diagrams can only be exported as PNG, many tools can not use the uselful ditaa syntax...

**Comment by danielbarry** [comment]
I think this feature would be awesome for creating documents that need extremely high quality, scalable, semi-compressed output. The SVG format may even have the effect of simplifying the ASCII to Image rendering code, scalable to bitmap graphics should be trivial for Java.

**Comment by jeanlazarou** [comment]
Do you think my PR (https://github.com/stathissideris/ditaa/pull/30) addresses your request?

**Comment by danielbarry** [comment]
Awesome! When will it be released in `aptitude`? Got a few people into using this tool now - will be amazing in LaTeX :)

**Comment by jeanlazarou** [comment]
PR https://github.com/stathissideris/ditaa/pull/30 was merged, can some one validate thet it addresses the issue as expected? If so, close this issue.

**Comment by stathissideris** [comment]
Yes, please have a look at the latest release!

**Comment by ulysses4ever** [comment]
Should this be closed?
