### ISSUE TITLE
Move to Gradle for building?

### ISSUE THREAD

**Issue by aadrian** [stathissideris/ditaa#25]
Hi,

Any chance moving to Gradle for building ditaa?

**Comment by stathissideris** [comment]
I have just moved it to leiningen (the Clojure build tool), because I will gradually port ditaa to Clojure. I'm planning to add instructions for building an uberjar (but it's pretty much standard so you can figure it out by reading leiningen's docs)

**Comment by aadrian** [comment]
> I will gradually port ditaa to Clojure

Great to hear that :) 

>  just moved it to leiningen

IMHO https://github.com/gradle-clojure/gradle-clojure would have been an easier path.
