### ISSUE TITLE
Is it possible to write subscript?

### ISSUE THREAD

**Issue by ag91** [stathissideris/ditaa#29]
Hello,

Thanks to maintain this piece of software, it is really an useful tool!
I was wandering if it allows to write subscript: I tried something LaTex-ish like k_1, but that does not work.
Is this supported?

**Comment by stathissideris** [comment]
Unfortunately this is not supported.

**Comment by ju-sh** [comment]
Unicode subscript characters (or at least what look them) could help. Like `k₁`.
