### ISSUE TITLE
Outdated Ubuntu Version

### ISSUE THREAD

**Issue by danielbarry** [stathissideris/ditaa#32]
The Ubuntu version of `ditaa` appears to be out of date in the `aptitude` (`apt-get`) package manager. I've been excited for a while to get the SVG image output update: https://github.com/stathissideris/ditaa/pull/30

The man page (`man ditaa`) produces no hint of these changes arriving, so this may just be a documentation issue:

    DITAA(1)                    General Commands Manual                   DITAA(1)
    
    NAME
           ditaa - convert ASCII diagrams into proper bitmap graphics
    
    SYNOPSIS
           ditaa [options] input [output]
    
    DESCRIPTION
           This manual page documents briefly the ditaa command.
    
           DiTAA  is  a small command-line utility that can convert diagrams drawn
           using ASCII art  ("drawings"  that  contain  characters  that  resemble
           lines, like | / and -), into proper bitmap graphics.
    
           DiTAA  also uses special markup syntax to increase the possibilities of
           shapes and symbols that can be rendered.
    
    OPTIONS
           --help Show summary of options.
    
           -v, --verbose
                  Makes ditaa more verbose.
    
           -A, --no-antialias
                  Turns anti-aliasing off.
    
           -d, --debug
                  Renders the debug grid over the resulting image.
    
           -E, --no-separation
                  Prevents the separation of common edges of shapes.
    
           -e ENCODING, --encoding ENCODING
                  The encoding of the input file.
    
           -h, --html
                  In this case the input is an HTML file. The contents of the <pre
                  class="textdiagram">  tags are rendered as diagrams and saved in
                  the images directory and a new HTML file is  produced  with  the
                  appropriate <img> tags.
    
           -o, --overwrite
                  If  the  filename  of  the  destination image already exists, an
                  alternative  name  is  chosen.   If  the  overwrite  option   is
                  selected, the image file is instead overwriten.
    
           -r, --round-corners
                  Causes all corners to be rendered as round corners.
    
           -s SCALE, --scale SCALE
                  A natural number that determines the size of the rendered image.
                  The units are fractions of the default  size  (2.5  renders  1.5
                  times bigger than the default).
    
           -S, --no-shadows
                  Turns off the drop-shadow effect.
    
           -t TABS, --tabs TABS
                  Tabs  are normally interpreted as 8 spaces but it is possible to
                  change that using this option. It is not advisable to  use  tabs
                  in your diagrams.
    
    AUTHOR
           DiTAA was written by Efstathios (Stathis) Sideris.
    
           This  manual  page was written by David Paleino <dapal@debian.org>, for
           the Debian project (and may be used by others).
    
                                    April 15, 2010                        DITAA(1)

**Comment by stathissideris** [comment]
This is not surprising, I did merge SVG functionality a few days ago, but I did a release only just now! I'm not sure how long it's going to get for this to get to Ubuntu (I'm not the ditaa package maintainer there), but if you need SVG now, just use the jar from the [0.11.0 release](https://github.com/stathissideris/ditaa/releases/tag/v0.11.0)
