### ISSUE TITLE
Font size is not fixed

### ISSUE THREAD

**Issue by QiangF** [stathissideris/ditaa#51]
When I have CJK characters in shapes, the same character has different sizes in different shapes.

**Comment by dakusui** [comment]
This person: https://github.com/luozengbin seems to share a patched version of ditaa as jditaa.jar for Japanese handling and it might work for you.
https://github.com/luozengbin/dot.emacs.d/tree/master/extra/org-ditaa.

I think this issue is a duplicate of Issue #34 .

**Comment by QiangF** [comment]
Thank you! I have found an alternative https://github.com/aafigure/aafigure
