### ISSUE TITLE
ditaa slowly eats all available ram and never outputs a file

### ISSUE THREAD

**Issue by void-witch** [stathissideris/ditaa#62]
when running ditaa on the following diagram with `java -jar ditaa-0.11.0-standalone.jar test.dit test.jpg`, the jvm process consumes all available ram on my 32 gig system over a minute and never actually produces an image before i kill it

```ditaa
+------+
| test |
+------+
```

**Comment by ghost** [comment]
i think this was an issue with my jvm install, since ditaa now works fine
